easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Profile
        - App\Entity\Sortie
        - App\Entity\FOSUserBundle\User
        - App\Entity\TypeSortie
        - App\Entity\Departement
        - App\Entity\Region
        - App\Entity\Ville
