fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\FOSUserBundle\User
    from_email:
        address: 'zaama.contact@gmail.com'
        sender_name: 'Liess'

    registration:
        confirmation:
            #from_email: # Use this node only if you don't want the global email address for the confirmation email
                #address:        ...
                #sender_name:    ...
            enabled:    true # change to true for required email confirmation
            template:   'FOSUserBundle/Registration/email.txt.twig'
        form:
            type: App\Form\FOSUserBundle\RegistrationFormType
            #name: fos_user_registration
    resetting:
        retry_ttl:            3600
        token_ttl:            86400
        email:
            template:             'FOSUserBundle/Resetting/email.txt.twig'
            from_email:
                address: 'zaama.contact@gmail.com' # Required
                sender_name: 'Liess' # Required
        form:
            type:                 FOS\UserBundle\Form\Type\ResettingFormType
            name:                 fos_user_resetting_form
            validation_groups:
                # Defaults:
                - ResetPassword
                - Default
