swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    host : email-smtp.eu-west-1.amazonaws.com
    username: AKIAIKI4M6QALHSSVGAQ
    password: BOm+ZhO3NvNILzr4bsGgznMoYqOr2OPGFcVkfLfDRtLq
    encryption: tls
 
